spring:
  config:
    activate:
      on-profile: "default"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chess
    username: root
    password: root

#  sql:
#    init:
#      mode: always

  mvc:
    hiddenmethod:
      filter:
        enabled: true
